# Default values for application.
environment: dev
angular:
  appName: angular-ui
  image: <from-release>
  port: 4200
  type: ClusterIP

api:
  appName: api
  image: <from-release>
  port: 80
  type: ClusterIP

ingress:
  secretName: tls-secret
  hostName: hmb-dev-ops-app-dev.eastus.cloudapp.azure.com
  certificateOwnerEmail: pjb2@hmbnet.com