# Default values for application.
environment: dev
angular:
  appName: angular-ui
  image: <from-release>
  port: 4200
  type: LoadBalancer

api:
  appName: api
  image: <from-release>
  port: 80
  type: LoadBalancer

ingress:
  secretName: tls-secret