# Default values for application.
environment: dev
angular:
  appName: angular-ui
  image: <from-release>
  port: 4200
  type: ClusterIP

api:
  appName: api
  image: <from-release>
  port: 5001
  type: ClusterIP

ingress:
  secretName: tls-secret