apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.angularReservationUI.appName }}
  labels:
    app: {{ .Values.angularReservationUI.appName }}
spec:
  type: {{ .Values.angularReservationUI.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.angularReservationUI.port }}
  selector:
    app: {{ .Values.angularReservationUI.appName }}