apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.angular.appName }}
  labels:
    app: {{ .Values.angular.appName }}
spec:
  type: {{ .Values.angular.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.angular.port }}
  selector:
    app: {{ .Values.angular.appName }}