apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.appName }}
  labels:
    app: {{ .Values.api.appName }}
spec:
  type: {{ .Values.api.type }}
  ports:
    - port: 443
      targetPort: {{ .Values.api.port }}
  selector:
    app: {{ .Values.api.appName }}