apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-rules-api
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /api
spec:
  tls:
  - hosts:
    - bmw-ref-arch.eastus.cloudapp.azure.com
    secretName: {{ .Values.ingress.secretName }}
  rules:
  - host: bmw-ref-arch.eastus.cloudapp.azure.com
    http:
      paths:
      - path: /api
        backend:
          serviceName: {{ .Values.api.appName }}
          servicePort: 80