# Default values for application.
environment: dev
angular:
  appName: angular
  port: 4200
  type: ClusterIP
  configMapName: angular-config-json
  image: patrickbadley/angularfrontend:367

api:
  appName: api
  port: 80
  type: ClusterIP
  image: patrickbadley/webapibackend:3367
