# Default values for application.
environment: dev
angular:
  appName: angular
  port: 4200
  type: ClusterIP
  configMapName: angular-config-json
  image: patrickbadley/angularfrontend:367

api:
  appName: api
  port: 80
  type: ClusterIP
  image: patrickbadley/webapibackend:3367

ingress:
  secretName: tls-secret
  hostName: developyourk8s.eastus.cloudapp.azure.com
  certificateOwnerEmail: pjb2@hmbnet.com

features:
  mapEnabled: false