---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: angular
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.angular: glob:*
    flux.weave.works/tag.api: glob:*
spec:
  chart:
    git: git@github.com:patrickbadley/devops-team-flux-config.git
    path: charts/angular
  releaseName: angular
  values:
    environment: default

    angular:
      replicaCount: 1
      image: devopsteam.azurecr.io/angularfrontend:3183

    api:
      replicaCount: 1
      image: devopsteam.azurecr.io/webapibackend:3185
