apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-rules-api
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.hostName }}
    secretName: {{ .Values.ingress.secretName }}
  rules:
  - host: {{ .Values.ingress.hostName }}
    http:
      paths:
      - path: /api
        backend:
          serviceName: {{ .Values.api.appName }}
          servicePort: 80